# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Register git hooks: pre-commit install --install-hooks
# - Run on all files:   pre-commit run --all-files

repos:
  # general
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, main]

  # python
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--line-length=88", "--exclude=/nebari/template/"]

  # terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-write=true

  # markdown
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        files: ^docs/
        name: mdformat
        entry: mdformat --wrap=120 --number --end-of-line=lf
        language: python
        types: [markdown]
        minimum_pre_commit_version: "2.0.0"
        additional_dependencies:
          - mdformat-tables
